"""add storage key and processing status with auto enum

Revision ID: fe3d1f3daef2
Revises: 0b2db9e0a894
Create Date: 2025-10-14 13:55:17.376966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3d1f3daef2'
down_revision: Union[str, Sequence[str], None] = '0b2db9e0a894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types
    processing_status_enum = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processing_status')
    processing_status_enum.create(op.get_bind(), checkfirst=True)


    op.add_column('knowledge_modules', sa.Column('file_storage_key', sa.String(length=255), nullable=True))
    op.add_column('knowledge_modules', sa.Column('processing_status', processing_status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_modules', 'processing_status')
    op.drop_column('knowledge_modules', 'file_storage_key')
    
    # Drop enum types
    processing_status_enum = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processing_status')
    processing_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

# Post-generation: This file may be automatically modified by env.py hooks
